languageCode = "ja"
title = "Something Poetical Private"
baseURL = "https://m16Takahiro.github.io"
theme = "beautifulhugo"

[Author]
  subtitle = "詩的で私的な、物語への感想を書いています。"
  name = "515 Hikaru"
  email = "12kojima.takahiro@gmail.com"
  github = "m16Takahiro"
  twitter = "515hikaru"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/m16Takahiro"
    weight = 1

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/515hikaru"
    weight = 1

[[menu.main]]
    name = "Other Blog"
    url = "http://hikaru515.hatenablog.com/"
    weight = 1
